### ISSUE TITLE
no-arrow-functions - Fix has invalid range

### ISSUE THREAD

**Issue by sgtwilko** [darrinholst/eslint-plugin-cucumber#19]
ESLint version 8.7.0,
eslint-plugin-cucumber version 1.4.0

When using the no-arrow-functions I get the following error:

``` 
AssertionError [ERR_ASSERTION]: Fix has invalid range: {
  "range": [
    null,
    null
  ],
  "text": "function() "
}
    at assertValidFix (\node_modules\eslint\lib\linter\report-translator.js:125:9)
    at normalizeFixes (\node_modules\eslint\lib\linter\report-translator.js:200:5)
    at \node_modules\eslint\lib\linter\report-translator.js:364:49
    at Object.report (\node_modules\eslint\lib\linter\linter.js:1050:41)
    at CallExpression (\node_modules\eslint-plugin-cucumber\lib\rules\no-arrow-functions.js:101:19)
    at ruleErrorHandler (\node_modules\eslint\lib\linter\linter.js:1079:28)
    at \node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (\node_modules\eslint\lib\linter\node-event-generator.js:297:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
```

**Comment by darrinholst** [comment]
resolved with f0b2a2fcb36e39c3067142de509933b122acfc6b
